// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// suf_stats_nrm_c_DeepState_TestHarness_generation.cpp and suf_stats_nrm_c_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List suf_stats_nrm_c(const IntegerVector& booklet_id, const IntegerVector& booklet_score, const IntegerVector& item_id, const IntegerVector& item_score, const int nit, const int max_score);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector booklet_id  = RcppDeepState_IntegerVector();
  qs::c_qsave(booklet_id,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/suf_stats_nrm_c/inputs/booklet_id.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "booklet_id values: "<< booklet_id << std::endl;
  IntegerVector booklet_score  = RcppDeepState_IntegerVector();
  qs::c_qsave(booklet_score,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/suf_stats_nrm_c/inputs/booklet_score.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "booklet_score values: "<< booklet_score << std::endl;
  IntegerVector item_id  = RcppDeepState_IntegerVector();
  qs::c_qsave(item_id,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/suf_stats_nrm_c/inputs/item_id.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "item_id values: "<< item_id << std::endl;
  IntegerVector item_score  = RcppDeepState_IntegerVector();
  qs::c_qsave(item_score,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/suf_stats_nrm_c/inputs/item_score.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "item_score values: "<< item_score << std::endl;
  IntegerVector nit(1);
  nit[0]  = RcppDeepState_int();
  qs::c_qsave(nit,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/suf_stats_nrm_c/inputs/nit.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nit values: "<< nit << std::endl;
  IntegerVector max_score(1);
  max_score[0]  = RcppDeepState_int();
  qs::c_qsave(max_score,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/suf_stats_nrm_c/inputs/max_score.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "max_score values: "<< max_score << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    suf_stats_nrm_c(booklet_id,booklet_score,item_id,item_score,nit[0],max_score[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
