// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// reg_2d_DeepState_TestHarness_generation.cpp and reg_2d_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix reg_2d(NumericMatrix& y_vec, NumericMatrix& w_vec, int metric);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix y_vec  = RcppDeepState_NumericMatrix();
  std::string y_vec_t = "/home/akhila/fuzzer_packages/fuzzedpackages/UniIsoRegression/inst/testfiles/reg_2d/libFuzzer_reg_2d/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_y_vec.qs";
  qs::c_qsave(y_vec,y_vec_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y_vec values: "<< y_vec << std::endl;
  NumericMatrix w_vec  = RcppDeepState_NumericMatrix();
  std::string w_vec_t = "/home/akhila/fuzzer_packages/fuzzedpackages/UniIsoRegression/inst/testfiles/reg_2d/libFuzzer_reg_2d/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_w_vec.qs";
  qs::c_qsave(w_vec,w_vec_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "w_vec values: "<< w_vec << std::endl;
  IntegerVector metric(1);
  metric[0]  = RcppDeepState_int();
  std::string metric_t = "/home/akhila/fuzzer_packages/fuzzedpackages/UniIsoRegression/inst/testfiles/reg_2d/libFuzzer_reg_2d/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_metric.qs";
  qs::c_qsave(metric,metric_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "metric values: "<< metric << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    reg_2d(y_vec,w_vec,metric[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
