// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// im_booklet_score_DeepState_TestHarness_generation.cpp and im_booklet_score_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

std::vector<int> im_booklet_score(const IntegerVector& person_id, const IntegerVector& item_score);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector person_id  = RcppDeepState_IntegerVector();
  std::string person_id_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/im_booklet_score/libFuzzer_im_booklet_score/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_person_id.qs";
  qs::c_qsave(person_id,person_id_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "person_id values: "<< person_id << std::endl;
  IntegerVector item_score  = RcppDeepState_IntegerVector();
  std::string item_score_t = "/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/im_booklet_score/libFuzzer_im_booklet_score/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_item_score.qs";
  qs::c_qsave(item_score,item_score_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "item_score values: "<< item_score << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    im_booklet_score(person_id,item_score);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
