// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// mutate_booklet_score_DeepState_TestHarness_generation.cpp and mutate_booklet_score_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector mutate_booklet_score(const IntegerVector& person_id, const IntegerVector& booklet_id, const IntegerVector& item_score);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector person_id  = RcppDeepState_IntegerVector();
  qs::c_qsave(person_id,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/mutate_booklet_score/inputs/person_id.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "person_id values: "<< person_id << std::endl;
  IntegerVector booklet_id  = RcppDeepState_IntegerVector();
  qs::c_qsave(booklet_id,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/mutate_booklet_score/inputs/booklet_id.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "booklet_id values: "<< booklet_id << std::endl;
  IntegerVector item_score  = RcppDeepState_IntegerVector();
  qs::c_qsave(item_score,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/mutate_booklet_score/inputs/item_score.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "item_score values: "<< item_score << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    mutate_booklet_score(person_id,booklet_id,item_score);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
