// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// make_booklets_unsafe_DeepState_TestHarness_generation.cpp and make_booklets_unsafe_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List make_booklets_unsafe(const IntegerVector& person_id, IntegerVector& booklet_id, const IntegerVector& module_nbr, const IntegerVector& item_id, const IntegerVector& item_score, IntegerVector& booklet_score, IntegerVector& include_rsp, const IntegerVector& bk_nmod);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector person_id  = RcppDeepState_IntegerVector();
  qs::c_qsave(person_id,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/make_booklets_unsafe/inputs/person_id.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "person_id values: "<< person_id << std::endl;
  IntegerVector booklet_id  = RcppDeepState_IntegerVector();
  qs::c_qsave(booklet_id,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/make_booklets_unsafe/inputs/booklet_id.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "booklet_id values: "<< booklet_id << std::endl;
  IntegerVector module_nbr  = RcppDeepState_IntegerVector();
  qs::c_qsave(module_nbr,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/make_booklets_unsafe/inputs/module_nbr.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "module_nbr values: "<< module_nbr << std::endl;
  IntegerVector item_id  = RcppDeepState_IntegerVector();
  qs::c_qsave(item_id,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/make_booklets_unsafe/inputs/item_id.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "item_id values: "<< item_id << std::endl;
  IntegerVector item_score  = RcppDeepState_IntegerVector();
  qs::c_qsave(item_score,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/make_booklets_unsafe/inputs/item_score.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "item_score values: "<< item_score << std::endl;
  IntegerVector booklet_score  = RcppDeepState_IntegerVector();
  qs::c_qsave(booklet_score,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/make_booklets_unsafe/inputs/booklet_score.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "booklet_score values: "<< booklet_score << std::endl;
  IntegerVector include_rsp  = RcppDeepState_IntegerVector();
  qs::c_qsave(include_rsp,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/make_booklets_unsafe/inputs/include_rsp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "include_rsp values: "<< include_rsp << std::endl;
  IntegerVector bk_nmod  = RcppDeepState_IntegerVector();
  qs::c_qsave(bk_nmod,"/home/akhila/fuzzer_packages/fuzzedpackages/dexterMST/inst/testfiles/make_booklets_unsafe/inputs/bk_nmod.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bk_nmod values: "<< bk_nmod << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    make_booklets_unsafe(person_id,booklet_id,module_nbr,item_id,item_score,booklet_score,include_rsp,bk_nmod);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
