// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getZ_DeepState_TestHarness_generation.cpp and getZ_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::IntegerMatrix getZ(Rcpp::NumericMatrix pi_mat);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix pi_mat  = RcppDeepState_NumericMatrix();
  std::string pi_mat_t = "/home/akhila/fuzzer_packages/fuzzedpackages/NetMix/inst/testfiles/getZ/AFL_getZ/afl_inputs/" + std::to_string(t) + "_pi_mat.qs";
  qs::c_qsave(pi_mat,pi_mat_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pi_mat values: "<< pi_mat << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getZ(pi_mat);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
