// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// comp_vardeltas_DeepState_TestHarness_generation.cpp and comp_vardeltas_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::vec comp_vardeltas(const arma::mat& deltas);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream deltas_stream;
  arma::mat deltas  = RcppDeepState_mat();
  deltas_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/HTLR/inst/testfiles/comp_vardeltas/inputs/deltas");
  deltas_stream << deltas;
  std::cout << "deltas values: "<< deltas << std::endl;
  deltas_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    comp_vardeltas(deltas);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
